#!/usr/bin/env sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

PUBKEY=`$DIR/sol-pubkey`

# https://docs.solana.com/developing/clients/jsonrpc-api#getaccountinfo

solana account $PUBKEY
